name: CI/CD for WordPress

on:
  push:
    branches:
      - main  #khi có push lên nhánh main
  pull_request:
    branches:
      - main  #khi có pull nhánh main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
